# Generated by firewall-cli
*nat
:PREROUTING ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
#------------------------------------------------------------------------------
# Iptables custom rules
# Table 5 index 15
-A PREROUTING -i BR_LAN --src 0.0.0.0/0 --dst 192.168.100.1/32 -p tcp --dport 80 -j DNAT --to-destination 192.168.0.1:80
# Table 5 index 18
-A PREROUTING -i BR_LAN --src 0.0.0.0/0 --dst 192.168.100.1/32 -p tcp --dport 443 -j DNAT --to-destination 192.168.0.1:443
# Table 5 index 19
-A POSTROUTING -d 192.168.100.0/24 -j MASQUERADE
# Table 5 index 26
-I PREROUTING -i BR_LAN -p udp --dport 53 -s 0.0.0.0/0 -m string --string "getmodem" --algo bm -j DNAT --to-destination 192.168.0.1:53
# Table 5 index 27
-I PREROUTING -i cm0 -p udp --dport 53 -s 0.0.0.0/0 -m string --string "getmodem" --algo bm -j DNAT --to-destination 84.211.113.22:53
#------------------------------------------------------------------------------
# GWY => WAN, LAN...
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# WAN, LAN... => GWY
#------------------------------------------------------------------------------
# Table 0 index 1
-A PREROUTING -i BR_LAN -p icmp --icmp-type echo-request -d 192.168.0.1 -j ACCEPT
# Table 0 index 2
-A PREROUTING -i BR_LAN -p udp --source-port 68 -d 192.168.0.1 --destination-port 67 -j ACCEPT
# Table 0 index 4
-A PREROUTING -i BR_LAN -p tcp --source-port 1024:65535 -d 192.168.0.1 --destination-port 53 -j ACCEPT
# Table 0 index 4
-A PREROUTING -i BR_LAN -p udp --source-port 1024:65535 -d 192.168.0.1 --destination-port 53 -j ACCEPT
# Table 0 index 4
-A PREROUTING -i BR_LAN -p udp --source-port 53 -d 192.168.0.1 --destination-port 1024:65535 -j ACCEPT
# Table 0 index 7
-A PREROUTING -i BR_LAN -p tcp -d 192.168.0.1 --destination-port 80 -j ACCEPT
# Table 0 index 8
-A PREROUTING -i privbr -p tcp -d 172.31.255.40 --destination-port 80 -j ACCEPT
# Table 0 index 9
-A PREROUTING -i privbr -p tcp -d 172.31.255.40 --destination-port 8080 -j ACCEPT
# Table 0 index 10
-A PREROUTING -i cm0 -p tcp -d 84.211.113.22 --destination-port 7547 -j ACCEPT
# Table 0 index 11
-A PREROUTING -i BR_LAN -p icmp --icmp-type echo-request -d 84.211.113.22 -j ACCEPT
# Table 0 index 12
-A PREROUTING -i privbr -p tcp -d 172.31.255.40 --destination-port 23 -j ACCEPT
# Table 0 index 13
-A PREROUTING -i BR_LAN -p tcp -d 192.168.0.1 --destination-port 443 -j ACCEPT
#------------------------------------------------------------------------------
# LAN => WAN (NAT rules)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# Masquerading traffic from 0.0.0.0/0 to Device/IP/Interfaces/Interface[IP_DATA]
# Table 4 index 1
-A POSTROUTING -o cm0 -j SNAT --to-source 84.211.113.22
#------------------------------------------------------------------------------
# WAN => LAN (Portmapping)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# Interface X => Interface Y (Forwarding rules)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# Iptables custom rules
COMMIT
# Generated by firewall-cli
*mangle
:PREROUTING ACCEPT [0:0]
:INPUT ACCEPT [0:0]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
#------------------------------------------------------------------------------
# Iptables custom rules
#------------------------------------------------------------------------------
# GWY => WAN, LAN...
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# WAN, LAN... => GWY
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# LAN => WAN (NAT rules)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# WAN => LAN (Portmapping)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# Interface X => Interface Y (Forwarding rules)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# Iptables custom rules
COMMIT
# Generated by firewall-cli
*filter
:INPUT DROP [0:0]
:FORWARD DROP [0:0]
:OUTPUT DROP [0:0]
-I FORWARD -p tcp ! --syn  -m state --state NEW -j DROP
#------------------------------------------------------------------------------
# Loopback
-A INPUT -i lo -j ACCEPT
-A OUTPUT -o lo -j ACCEPT
#------------------------------------------------------------------------------
# Spoofing, MSS  & Bad addresses
-A INPUT -s 192.168.0.1 -j DROP
-A INPUT -s 84.211.113.22 -j DROP
-A INPUT -s 172.31.255.40 -j DROP
-A INPUT -s 172.31.255.40 -j DROP
-A INPUT -s 192.168.0.1 -j DROP
-A INPUT -s 84.211.113.22 -j DROP
-A FORWARD -p tcp -m tcp --tcp-flags SYN,RST SYN -j TCPMSS --clamp-mss-to-pmtu
#------------------------------------------------------------------------------
# Iptables custom rules
# Table 5 index 1
-A INPUT -i priv0 -j ACCEPT
# Table 5 index 2
-A OUTPUT -o priv0 -j ACCEPT
# Table 5 index 3
-A INPUT -i privbr -j ACCEPT
# Table 5 index 4
-A OUTPUT -o privbr -j ACCEPT
# Table 5 index 5
-A INPUT -i privbr:0 -j ACCEPT
# Table 5 index 6
-A OUTPUT -o privbr:0 -j ACCEPT
# Table 5 index 7
-A INPUT -i privbr:1 -j ACCEPT
# Table 5 index 8
-A OUTPUT -o privbr:1 -j ACCEPT
# Table 5 index 9
-A FORWARD -i BR_LAN -o BR_LAN -j ACCEPT
# Table 5 index 10
-A INPUT -p icmp -m icmp ! --icmp-type echo-request -j ACCEPT
# Table 5 index 11
-A OUTPUT -p icmp -m icmp ! --icmp-type echo-request -j ACCEPT
# Table 5 index 12
-A FORWARD -p icmp -m icmp ! --icmp-type echo-request -j ACCEPT
# Table 5 index 13
-A INPUT -i BR_LAN -p tcp --dst 192.168.0.1/32 --dport 80 -j ACCEPT
# Table 5 index 14
-A OUTPUT -o BR_LAN -p tcp --src 192.168.0.1/32 --sport 80 -j ACCEPT
# Table 5 index 16
-A INPUT -i BR_LAN -p tcp --dst 192.168.0.1/32 --dport 443 -j ACCEPT
# Table 5 index 17
-A OUTPUT -o BR_LAN -p tcp --src 192.168.0.1/32 --sport 443 -j ACCEPT
# Table 5 index 20
-A FORWARD -i BR_LAN -o privbr -p icmp --dst 192.168.100.0/24 -j ACCEPT
# Table 5 index 21
-A FORWARD --dst 192.168.100.1 -i BR_LAN -o privbr -p tcp -m multiport --dport 23 -m state --state ESTABLISHED,RELATED,NEW -j ACCEPT
# Table 5 index 22
-A FORWARD --source 192.168.100.1 -i privbr -o BR_LAN -p tcp -m multiport --sport 23 -m state --state ESTABLISHED,RELATED,NEW -j ACCEPT
# Table 5 index 23
-A FORWARD -i BR_LAN -o privbr -p udp --dport 161 --dst 192.168.100.0/24 -j ACCEPT
# Table 5 index 24
-A FORWARD -i privbr -o BR_LAN -p udp --sport 161 --src 192.168.100.0/24 -j ACCEPT
# Table 5 index 25
-I FORWARD -i BR_LAN --dst 172.31.255.45 -j DROP
# Table 5 index 28
-N syn-flood
# Table 5 index 29
-N icmp-flood
# Table 5 index 30
-N udp-flood
# Table 5 index 31
-A syn-flood -j DROP
# Table 5 index 32
-A icmp-flood -j DROP
# Table 5 index 33
-A udp-flood -j DROP
# Table 5 index 34
-I INPUT -p igmp -m comment --comment "Allow IGMP" -j ACCEPT
# Table 5 index 35
-I FORWARD -d 224.0.0.0/4 -i cm0 -m comment --comment "Allow multicast" -j ACCEPT
# Table 5 index 36
-I OUTPUT -d 224.0.0.0/4 -m comment --comment "Allow multicast" -j ACCEPT
#------------------------------------------------------------------------------
# GWY => WAN, LAN...
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# TFTP client : GWY => Device/IP/Interfaces/Interface[IP_BR_LAN]
# Table 1 index 1
-A OUTPUT -o BR_LAN -p udp -m state --state NEW -s 192.168.0.1 --source-port 1024:65535 --destination-port 69 -j ACCEPT
# Table 1 index 1
-A OUTPUT -o BR_LAN -p udp -m state --state ESTABLISHED -s 192.168.0.1 --source-port 1024:65535 --destination-port 1024:65535 -j ACCEPT
# Table 1 index 1
-A INPUT -i BR_LAN -p udp -m state --state ESTABLISHED,RELATED --source-port 1024:65535 -d 192.168.0.1 --destination-port 1024:65535 -j ACCEPT
#------------------------------------------------------------------------------
# PING client : GWY => Device/IP/Interfaces/Interface[IP_BR_LAN]
# Table 1 index 2
-A OUTPUT -o BR_LAN -p icmp --icmp-type echo-request -s 192.168.0.1 -j ACCEPT
# Table 1 index 2
-A INPUT -i BR_LAN -p icmp --icmp-type echo-reply -m state --state ESTABLISHED,RELATED -d 192.168.0.1 -j ACCEPT
#------------------------------------------------------------------------------
# HTTP client : GWY => Device/IP/Interfaces/Interface[IP_DATA]
# Table 1 index 4
-A OUTPUT -o cm0 -p tcp -s 84.211.113.22 --source-port 1024:65535 --destination-port 80 -j ACCEPT
# Table 1 index 4
-A INPUT -i cm0 -p tcp -m state --state ESTABLISHED,RELATED --source-port 80 -d 84.211.113.22 --destination-port 1024:65535 -j ACCEPT
#------------------------------------------------------------------------------
# PING client : GWY => Device/IP/Interfaces/Interface[IP_DATA]
# Table 1 index 5
-A OUTPUT -o cm0 -p icmp --icmp-type echo-request -s 84.211.113.22 -j ACCEPT
# Table 1 index 5
-A INPUT -i cm0 -p icmp --icmp-type echo-reply -m state --state ESTABLISHED,RELATED -d 84.211.113.22 -j ACCEPT
#------------------------------------------------------------------------------
# UPnP client : GWY => Device/IP/Interfaces/Interface[IP_BR_LAN]
# Table 1 index 6
-A OUTPUT -o BR_LAN -p udp -d 239.255.255.250 --destination-port 1900 -s 192.168.0.1 --source-port 1024:65535 -j ACCEPT
# Table 1 index 6
-A OUTPUT -o BR_LAN -p tcp -d 239.255.255.250 --destination-port 2869 -s 192.168.0.1 --source-port 1024:65535 -j ACCEPT
# Table 1 index 6
-A INPUT -i BR_LAN -p udp -m state --state NEW,ESTABLISHED --source-port 1024:65535 -d 192.168.0.1 --destination-port 1024:65535 -j ACCEPT
# Table 1 index 6
-A OUTPUT -o BR_LAN -p tcp -m state --state NEW,ESTABLISHED -s 192.168.0.1 --source-port 1024:65535 --destination-port 1024:65535 -j ACCEPT
# Table 1 index 6
-A INPUT -i BR_LAN -p tcp -m state --state ESTABLISHED -s 192.168.0.1 --source-port 1024:65535 --destination-port 1024:65535 -j ACCEPT
#------------------------------------------------------------------------------
# DHCP client : GWY => Device/IP/Interfaces/Interface[IP_DATA]
# Table 1 index 7
-A INPUT -i cm0 -p udp --source-port 67 --destination-port 68 -j ACCEPT
# Table 1 index 7
-A OUTPUT -o cm0 -p udp --source-port 68 --destination-port 67 -j ACCEPT
#------------------------------------------------------------------------------
# DNS client : GWY => Device/IP/Interfaces/Interface[IP_DATA]
# Table 1 index 8
-A OUTPUT -o cm0 -p udp -s 84.211.113.22 --source-port 1024:65535 --destination-port 53 -j ACCEPT
# Table 1 index 8
-A OUTPUT -o cm0 -p udp -s 84.211.113.22 --source-port 53 --destination-port 53 -j ACCEPT
# Table 1 index 8
-A INPUT -i cm0 -p udp -m state --state ESTABLISHED,RELATED  --source-port 53 -d 84.211.113.22 --destination-port 1024:65535 -j ACCEPT
# Table 1 index 8
-A INPUT -i cm0 -p udp -m state --state ESTABLISHED,RELATED  --source-port 53 -d 84.211.113.22 --destination-port 53 -j ACCEPT
# Table 1 index 8
-A OUTPUT -o cm0 -p tcp -s 84.211.113.22 --source-port 1024:65535 --destination-port 53 -j ACCEPT
# Table 1 index 8
-A INPUT -i cm0 -p tcp ! --syn --source-port 53 -d 84.211.113.22 --destination-port 1024:65535 -j ACCEPT
#------------------------------------------------------------------------------
# WAN, LAN... => GWY
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# PING server : Device/IP/Interfaces/Interface[IP_BR_LAN] => GWY
# Table 0 index 1
-A INPUT -i BR_LAN -p icmp --icmp-type echo-request -d 192.168.0.1 -j ACCEPT
# Table 0 index 1
-A OUTPUT -o BR_LAN -p icmp --icmp-type echo-reply -m state --state ESTABLISHED,RELATED -s 192.168.0.1 -j ACCEPT
#------------------------------------------------------------------------------
# DHCP server : Device/IP/Interfaces/Interface[IP_BR_LAN] => GWY
# Table 0 index 2
-A INPUT -i BR_LAN -p udp --source-port 68 --destination-port 67 -j ACCEPT
# Table 0 index 2
-A OUTPUT -o BR_LAN -p udp --source-port 67 --destination-port 68 -j ACCEPT
#------------------------------------------------------------------------------
# DNS server : Device/IP/Interfaces/Interface[IP_BR_LAN] => GWY
# Table 0 index 4
-A INPUT -i BR_LAN -p tcp --source-port 1024:65535 -d 192.168.0.1 --destination-port 53 -j ACCEPT
# Table 0 index 4
-A OUTPUT -o BR_LAN -p tcp ! --syn -s 192.168.0.1 --source-port 53 --destination-port 1024:65535 -j ACCEPT
# Table 0 index 4
-A INPUT -i BR_LAN -p udp --source-port 1024:65535 -d 192.168.0.1 --destination-port 53 -j ACCEPT
# Table 0 index 4
-A INPUT -i BR_LAN -p udp --source-port 53 -d 192.168.0.1 --destination-port 53 -j ACCEPT
# Table 0 index 4
-A OUTPUT -o BR_LAN -p udp -s 192.168.0.1 --source-port 53 --destination-port 1024:65535 -j ACCEPT
# Table 0 index 4
-A OUTPUT -o BR_LAN -p udp -s 192.168.0.1 --source-port 53 --destination-port 53 -j ACCEPT
# Table 0 index 4
-A INPUT -i BR_LAN -p udp --source-port 53 -d 192.168.0.1 --destination-port 1024:65535 -j ACCEPT
#------------------------------------------------------------------------------
# UPnP server : Device/IP/Interfaces/Interface[IP_BR_LAN] => GWY
# Table 0 index 6
-A INPUT -i BR_LAN -p udp --source-port 1024:65535 -d 239.255.255.250 --destination-port 1900 -j ACCEPT
# Table 0 index 6
-A OUTPUT -o BR_LAN -p udp -s 192.168.0.1 --source-port 1024:65535 -d 239.255.255.250 --destination-port 1900 -j ACCEPT
# Table 0 index 6
-A INPUT -i BR_LAN -p tcp --source-port 1024:65535 -d 239.255.255.250 --destination-port 2869 -j ACCEPT
# Table 0 index 6
-A OUTPUT -o BR_LAN -p udp -m state --state NEW,ESTABLISHED -s 192.168.0.1 --source-port 1024:65535 --destination-port 1024:65535 -j ACCEPT
# Table 0 index 6
-A INPUT -i BR_LAN -p tcp -m state --state NEW,ESTABLISHED --source-port 1024:65535 -d 192.168.0.1 --destination-port 1024:65535 -j ACCEPT
# Table 0 index 6
-A OUTPUT -o BR_LAN -p tcp -m state --state NEW,ESTABLISHED --destination-port 1024:65535 -s 192.168.0.1 --source-port 1024:65535 -j ACCEPT
#------------------------------------------------------------------------------
# CUSTOM [80] server : Device/IP/Interfaces/Interface[IP_BR_LAN] => GWY
# Table 0 index 7
-A INPUT -i BR_LAN -p tcp -d 192.168.0.1 --destination-port 80 -j ACCEPT
# Table 0 index 7
-A OUTPUT -o BR_LAN -p tcp -m state --state ESTABLISHED,RELATED -s 192.168.0.1 --source-port 80 -j ACCEPT
#------------------------------------------------------------------------------
# CUSTOM [80] server : Device/IP/Interfaces/Interface[PRIVBR0] => GWY
# Table 0 index 8
-A INPUT -i privbr -p tcp -d 172.31.255.40 --destination-port 80 -j ACCEPT
# Table 0 index 8
-A OUTPUT -o privbr -p tcp -m state --state ESTABLISHED,RELATED -s 172.31.255.40 --source-port 80 -j ACCEPT
#------------------------------------------------------------------------------
# CUSTOM [8080] server : Device/IP/Interfaces/Interface[PRIVBR0] => GWY
# Table 0 index 9
-A INPUT -i privbr -p tcp -d 172.31.255.40 --destination-port 8080 -j ACCEPT
# Table 0 index 9
-A OUTPUT -o privbr -p tcp -m state --state ESTABLISHED,RELATED -s 172.31.255.40 --source-port 8080 -j ACCEPT
#------------------------------------------------------------------------------
# CUSTOM [7547] server : Device/IP/Interfaces/Interface[IP_DATA] => GWY
# Table 0 index 10
-A INPUT -i cm0 -p tcp -d 84.211.113.22 --destination-port 7547 -j ACCEPT
# Table 0 index 10
-A OUTPUT -o cm0 -p tcp -m state --state ESTABLISHED,RELATED -s 84.211.113.22 --source-port 7547 -j ACCEPT
#------------------------------------------------------------------------------
# PING server : Device/IP/Interfaces/Interface[IP_BR_LAN] => GWY
# Table 0 index 11
-A INPUT -i BR_LAN -p icmp --icmp-type echo-request -d 84.211.113.22 -j ACCEPT
# Table 0 index 11
-A OUTPUT -o BR_LAN -p icmp --icmp-type echo-reply -m state --state ESTABLISHED,RELATED -s 84.211.113.22 -j ACCEPT
#------------------------------------------------------------------------------
# CUSTOM [23] server : Device/IP/Interfaces/Interface[PRIVBR0] => GWY
# Table 0 index 12
-A INPUT -i privbr -p tcp -d 172.31.255.40 --destination-port 23 -j ACCEPT
# Table 0 index 12
-A OUTPUT -o privbr -p tcp -m state --state ESTABLISHED,RELATED -s 172.31.255.40 --source-port 23 -j ACCEPT
#------------------------------------------------------------------------------
# CUSTOM [443] server : Device/IP/Interfaces/Interface[IP_BR_LAN] => GWY
# Table 0 index 13
-A INPUT -i BR_LAN -p tcp -d 192.168.0.1 --destination-port 443 -j ACCEPT
# Table 0 index 13
-A OUTPUT -o BR_LAN -p tcp -m state --state ESTABLISHED,RELATED -s 192.168.0.1 --source-port 443 -j ACCEPT
#------------------------------------------------------------------------------
# LAN => WAN (NAT rules)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# WAN => LAN (Portmapping)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# Interface X => Interface Y (Forwarding rules)
#------------------------------------------------------------------------------
#------------------------------------------------------------------------------
# SAMBA : Device/IP/Interfaces/Interface[IP_BR_LAN] => Device/IP/Interfaces/Interface[IP_DATA]
# EPMAP
# Table 2 index 1
-A FORWARD -i BR_LAN -p tcp -m state --state RELATED,ESTABLISHED -o cm0 --destination-port 135 -j DROP
# Table 2 index 1
-A FORWARD -i cm0 -p tcp -m state ! --state INVALID --source-port 135 -o BR_LAN -j DROP
# Table 2 index 1
-A FORWARD -i BR_LAN -p udp -m state --state ESTABLISHED -o cm0 --destination-port 135 -j DROP
# Table 2 index 1
-A FORWARD -i cm0 -p udp -m state --state NEW --source-port 135 -o BR_LAN -j DROP
# Netbios-NS
# Table 2 index 1
-A FORWARD -i BR_LAN -p tcp -m state --state RELATED,ESTABLISHED -o cm0 --destination-port 137 -j DROP
# Table 2 index 1
-A FORWARD -i cm0 -p tcp -m state ! --state INVALID --source-port 137 -o BR_LAN -j DROP
# Table 2 index 1
-A FORWARD -i BR_LAN -p udp -m state --state ESTABLISHED -o cm0 --destination-port 137 -j DROP
# Table 2 index 1
-A FORWARD -i cm0 -p udp -m state --state NEW --source-port 137 -o BR_LAN -j DROP
# Netbios-DGM
# Table 2 index 1
-A FORWARD -i BR_LAN -p udp -m state --state ESTABLISHED -o cm0 --destination-port 138 -j DROP
# Table 2 index 1
-A FORWARD -i cm0 -p udp -m state --state NEW --source-port 138 -o BR_LAN -j DROP
# Netbios-SSN
# Table 2 index 1
-A FORWARD -i BR_LAN -p tcp -m state --state RELATED,ESTABLISHED -o cm0 --destination-port 139 -j DROP
# Table 2 index 1
-A FORWARD -i cm0 -p tcp -m state ! --state INVALID --source-port 139 -o BR_LAN -j DROP
# SMB/IP
# Table 2 index 1
-A FORWARD -i BR_LAN -p tcp -m state --state RELATED,ESTABLISHED -o cm0 --destination-port 445 -j DROP
# Table 2 index 1
-A FORWARD -i cm0 -p tcp -m state ! --state INVALID --source-port 445 -o BR_LAN -j DROP
# Table 2 index 1
-A FORWARD -i BR_LAN -p udp -m state --state ESTABLISHED -o cm0 --destination-port 445 -j DROP
# Table 2 index 1
-A FORWARD -i cm0 -p udp -m state --state NEW --source-port 445 -o BR_LAN -j DROP
#------------------------------------------------------------------------------
# CUSTOM [any] : Device/IP/Interfaces/Interface[IP_BR_LAN] => Device/IP/Interfaces/Interface[IP_DATA]
# Table 2 index 2
-A FORWARD -i BR_LAN -p tcp -o cm0 -j ACCEPT
# Table 2 index 2
-A FORWARD -i cm0 -p tcp -m state --state RELATED,ESTABLISHED -o BR_LAN -j ACCEPT
# Table 2 index 2
-A FORWARD -i BR_LAN -p udp -o cm0 -j ACCEPT
# Table 2 index 2
-A FORWARD -i cm0 -p udp -m state --state RELATED,ESTABLISHED -o BR_LAN -j ACCEPT
# Table 2 index 2
-A FORWARD -i BR_LAN -p icmp -o cm0 -j ACCEPT
# Table 2 index 2
-A FORWARD -i cm0 -p icmp -m state --state RELATED,ESTABLISHED -o BR_LAN -j ACCEPT
# Table 2 index 2
-A FORWARD -i BR_LAN -p gre -o cm0 -j ACCEPT
# Table 2 index 2
-A FORWARD -i cm0 -p gre -m state --state RELATED,ESTABLISHED -o BR_LAN -j ACCEPT
# Table 2 index 2
-A FORWARD -i BR_LAN -p ah -o cm0 -j ACCEPT
# Table 2 index 2
-A FORWARD -i cm0 -p ah -m state --state RELATED,ESTABLISHED -o BR_LAN -j ACCEPT
# Table 2 index 2
-A FORWARD -i BR_LAN -p esp -o cm0 -j ACCEPT
# Table 2 index 2
-A FORWARD -i cm0 -p esp -m state --state RELATED,ESTABLISHED -o BR_LAN -j ACCEPT
#------------------------------------------------------------------------------
# DNS : Device/IP/Interfaces/Interface[IP_BR_GUEST] => Device/IP/Interfaces/Interface[IP_BR_LAN]
# Table 2 index 3
-A FORWARD -i (null) -p udp -s 0.0.0.0/0 --source-port 1024:65535 -o BR_LAN -d 192.168.0.1/24 --destination-port 53 -j ACCEPT
# Table 2 index 3
-A FORWARD -i (null) -p udp -s 0.0.0.0/0 --source-port 53 -o BR_LAN -d 192.168.0.1/24 --destination-port 53 -j ACCEPT
# Table 2 index 3
-A FORWARD -i BR_LAN -p udp -s 192.168.0.1/24 --source-port 53 -o (null) -d 0.0.0.0/0 --destination-port 1024:65535 -j ACCEPT
# Table 2 index 3
-A FORWARD -i BR_LAN -p udp -s 192.168.0.1/24 --source-port 53 -o (null) -d 0.0.0.0/0 --destination-port 53 -j ACCEPT
# Table 2 index 3
-A FORWARD -i (null) -p tcp -s 0.0.0.0/0 --source-port 1024:65535 -o BR_LAN -d 192.168.0.1/24 --destination-port 53 -j ACCEPT
# Table 2 index 3
-A FORWARD -i BR_LAN -p tcp ! --syn -s 192.168.0.1/24 --source-port 53 -o (null) -d 0.0.0.0/0 --destination-port 1024:65535 -j ACCEPT
#------------------------------------------------------------------------------
# CUSTOM [any] : Device/IP/Interfaces/Interface[IP_BR_GUEST] => Device/IP/Interfaces/Interface[IP_DATA]
# Table 2 index 4
-A FORWARD -i (null) -p tcp -o cm0 -j ACCEPT
# Table 2 index 4
-A FORWARD -i cm0 -p tcp -m state --state RELATED,ESTABLISHED -o (null) -j ACCEPT
# Table 2 index 4
-A FORWARD -i (null) -p udp -o cm0 -j ACCEPT
# Table 2 index 4
-A FORWARD -i cm0 -p udp -m state --state RELATED,ESTABLISHED -o (null) -j ACCEPT
# Table 2 index 4
-A FORWARD -i (null) -p icmp -o cm0 -j ACCEPT
# Table 2 index 4
-A FORWARD -i cm0 -p icmp -m state --state RELATED,ESTABLISHED -o (null) -j ACCEPT
# Table 2 index 4
-A FORWARD -i (null) -p gre -o cm0 -j ACCEPT
# Table 2 index 4
-A FORWARD -i cm0 -p gre -m state --state RELATED,ESTABLISHED -o (null) -j ACCEPT
# Table 2 index 4
-A FORWARD -i (null) -p ah -o cm0 -j ACCEPT
# Table 2 index 4
-A FORWARD -i cm0 -p ah -m state --state RELATED,ESTABLISHED -o (null) -j ACCEPT
# Table 2 index 4
-A FORWARD -i (null) -p esp -o cm0 -j ACCEPT
# Table 2 index 4
-A FORWARD -i cm0 -p esp -m state --state RELATED,ESTABLISHED -o (null) -j ACCEPT
#------------------------------------------------------------------------------
# Iptables custom rules
COMMI